import type { DriveItem } from "./types"

export const mockData: DriveItem[] = [
  {
    id: "root",
    name: "My Drive",
    parentId: null,
    type: "folder",
    createdAt: new Date().toISOString(),
    childrenCount: 3,
  },
  {
    id: "folder1",
    name: "Documents",
    parentId: "root",
    type: "folder",
    createdAt: new Date().toISOString(),
    childrenCount: 2,
  },
  {
    id: "folder2",
    name: "Images",
    parentId: "root",
    type: "folder",
    createdAt: new Date().toISOString(),
    childrenCount: 2,
  },
  {
    id: "folder3",
    name: "Projects",
    parentId: "root",
    type: "folder",
    createdAt: new Date().toISOString(),
    childrenCount: 1,
  },
  {
    id: "file1",
    name: "Project Plan",
    parentId: "folder1",
    type: "file",
    extension: "pdf",
    size: 250,
    createdAt: new Date().toISOString(),
  },
  {
    id: "file2",
    name: "Meeting Notes",
    parentId: "folder1",
    type: "file",
    extension: "docx",
    size: 125,
    createdAt: new Date().toISOString(),
  },
  {
    id: "file3",
    name: "Vacation Photo",
    parentId: "folder2",
    type: "file",
    extension: "jpg",
    size: 1024,
    createdAt: new Date().toISOString(),
  },
  {
    id: "file4",
    name: "Profile Picture",
    parentId: "folder2",
    type: "file",
    extension: "png",
    size: 512,
    createdAt: new Date().toISOString(),
  },
  {
    id: "folder4",
    name: "Web Development",
    parentId: "folder3",
    type: "folder",
    createdAt: new Date().toISOString(),
    childrenCount: 2,
  },
  {
    id: "file5",
    name: "React Notes",
    parentId: "folder4",
    type: "file",
    extension: "md",
    size: 45,
    createdAt: new Date().toISOString(),
  },
  {
    id: "file6",
    name: "TypeScript Cheatsheet",
    parentId: "folder4",
    type: "file",
    extension: "pdf",
    size: 320,
    createdAt: new Date().toISOString(),
  },
]
