import type { File, Folder} from "./types"

export const mockDataFolder: Folder[] = [
  {
    id: 1,
    name: "My Drive",
    parentId: null,
    createdAt: new Date(),
    updatedAt: new Date(),
    childrenCount: 3,
  },
  {
    id: 2,
    name: "Documents",
    parentId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    childrenCount: 2,
  },
  {
    id: 3,
    name: "Images",
    parentId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    childrenCount: 2,
  },
  {
    id: 4,
    name: "Projects",
    parentId: 1,
    createdAt: new Date(),
    updatedAt: new Date(),
    childrenCount: 1,
  },
  {
    id: 5,
    name: "Web Development",
    parentId: 4,
    createdAt: new Date(),
    updatedAt: new Date(),
    childrenCount: 2,
  },
]

export const mockDataFile: File[] = [
  {
    id: 1,
    name: "Project Plan",
    url: "/files/project-plan.pdf",
    parentId: 2,
    type: "file",
    extension: "pdf",
    size: 250,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    name: "Meeting Notes",
    url: "/files/meeting-notes.docx",
    parentId: 2,
    type: "file",
    extension: "docx",
    size: 125,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    name: "Vacation Photo",
    url: "/files/vacation-photo.jpg",
    parentId: 3,
    type: "file",
    extension: "jpg",
    size: 1024,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    name: "Profile Picture",
    url: "/files/profile-picture.png",
    parentId: 3,
    type: "file",
    extension: "png",
    size: 512,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    name: "React Notes",
    url: "/files/react-notes.md",
    parentId: 5,
    type: "file",
    extension: "md",
    size: 45,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    name: "TypeScript Cheatsheet",
    url: "/files/typescript-cheatsheet.pdf",
    parentId: 5,
    type: "file",
    extension: "pdf",
    size: 320,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockData: {files: File[], folders: Folder[]} = {
  folders: mockDataFolder,
  files: mockDataFile,
}
